services:
  app:
    build: .
    container_name: taxodino-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /app/__pycache__
    env_file:
      - .env
    restart: unless-stopped